# Generated by Django 4.2.5 on 2023-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='содержимое'),
        ),
    ]
